apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-app-config
  namespace: streaming-app
data:
  aws-region: {{ .Values.aws.region | quote }}
  aws-s3-bucket: {{ .Values.aws.s3Bucket | quote }}
  aws-cdn-url: {{ .Values.aws.cdnUrl | quote }}
  mongo-uri: {{ .Values.mongodb.uri | quote }}
  streaming-public-url: "/api/streaming"
  client-url: {{ .Values.clientUrl | quote }}