apiVersion: v1
kind: Secret
metadata:
  name: streaming-app-secrets
  namespace: default
type: Opaque
data:
  aws-access-key-id: {{ .Values.aws.accessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.aws.secretAccessKey | b64enc | quote }}
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}